### PR TITLE
fix(schema): properly handle array defaults

### LINKED ISSUE #6688: Migrator: Array of embeddables not properly assigned default value
### Describe the bug

The title already describes it quite good. I am trying to set an empty array as default for an array of embeddables but the migrator does not create a proper SQL statement for that.

So the following entities:
```ts
@Embeddable()
export class Account {
  @Property()
  accountName: string;

  @Property()
  accountPassword: string;
}

@Entity()
export class User {
  @PrimaryKey()
  id: number;

  @Embedded({ array: true, default: [] })
  accounts: Account[] = [];
}
```

result in this migration:

```ts
override async up(): Promise<void> {
    this.addSql(`create table "user" ("id" serial primary key, "accounts" jsonb not null default );`);
}
```

Our current workaround is:

```ts
@Entity()
export class User {
  @PrimaryKey()
  id: number;

  @Embedded({ array: true, defaultRaw: "'[]'" })
  accounts: Account[] = [];
}
```

### Reproduction

https://github.com/NicklasKnell/reproduction/tree/array-default

### What driver are you using?

@mikro-orm/postgresql

### MikroORM version

6.4.15

### Node.js version

22.9.0

### Operating system

Ubuntu

### Validations

- [x] Read the [Contributing Guidelines](https://github.com/mikro-orm/mikro-orm/blob/master/CONTRIBUTING.md).
- [x] Read the [docs](https://mikro-orm.io/docs).
- [x] Check that there isn't [already an issue](https://github.com/mikro-orm/mikro-orm/issues) that reports the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mikro-orm/mikro-orm/discussions) or join our [Discord](https://discord.gg/w8bjxFHS7X).
- [x] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by Ruby184**
Fixes #6688. While testing across all databases, MySQL was failing with the following error:

```sql
DriverException: create table `a` (
  `id` int unsigned not null auto_increment primary key,
  `languages` text not null default 'en',
  `accounts` json not null default '[]',
  `items` text not null default ''
) default character set utf8mb4 engine = InnoDB;
- BLOB, TEXT, GEOMETRY or JSON column 'languages' can't have a default value
```
See: https://dev.mysql.com/doc/refman/9.0/en/data-type-defaults.html

> The [BLOB](https://dev.mysql.com/doc/refman/9.0/en/blob.html), [TEXT](https://dev.mysql.com/doc/refman/9.0/en/blob.html), GEOMETRY, and [JSON](https://dev.mysql.com/doc/refman/9.0/en/json.html) data types can be assigned a default value only if the value is written as an expression, even if the expression value is a literal

Fixed by wrapping the default value in an expression when the column type is one of the types mentioned above.

### CODE REVIEW

File: packages/core/src/metadata/MetadataDiscovery.ts [hunk 1]
```diff
@@ -1307,8 +1307,12 @@ export class MetadataDiscovery {
...
     }
 
-    if (prop.customType instanceof ArrayType && Array.isArray(prop.default)) {
-      val = prop.customType.convertToDatabaseValue(prop.default, this.platform)!;
+    if (Array.isArray(prop.default)) {
+      if (prop.customType instanceof ArrayType) {
+        val = prop.customType.convertToDatabaseValue(prop.default, this.platform)!;
+      } else if (prop.kind === ReferenceKind.EMBEDDED && prop.array) {
+        val = this.platform.convertJsonToDatabaseValue(prop.default) as string;
+      }
```
Comment (B4nan) [inline packages/core/src/metadata/MetadataDiscovery.ts]: so `prop.customType` is not set for the embedded array properties? maybe it would be a better fix to set it during the discovery (to the JSON type), but maybe it will break more things, in such case i would be fine with what you did

File: tests/issues/GH6688.test.ts [hunk 2]
```diff
@@ -0,0 +1,65 @@
...
+  items: Opt<EnumItems[]> = [];
+
+}
+
+const options = {
+  'sqlite': { dbName: ':memory:' },
+  'better-sqlite': { dbName: ':memory:' },
+  'mysql': { dbName: 'default_array_values', port: 3308 },
+  'mariadb': { dbName: 'default_array_values', port: 3309 },
+  'postgresql': { dbName: 'default_array_values' },
```
Comment (B4nan) [inline tests/issues/GH6688.test.ts:40]: can you test mssql too please?

**Review by B4nan — CHANGES_REQUESTED** [review]

File: packages/core/src/metadata/MetadataDiscovery.ts (hunk 1 above)
Comment (Ruby184) [reply packages/core/src/metadata/MetadataDiscovery.ts]: Yes, it was not set. I looked into it and added a condition to apply the JsonType custom type in the case of embedded properties, but a few tests broke. 😕 I’ll try to fix that.

Comment (Ruby184) [reply packages/core/src/metadata/MetadataDiscovery.ts]: I’ve fixed the tests - searched for `customType instanceof JsonType` and updated the conditions where necessary. So it shouldn’t break anything.

**Review by B4nan — APPROVED** [review]
thanks!
