### PR TITLE
fix(core): improve TS detection logic

### LINKED ISSUE #6491: Regression: v6.4.9 breaks tsx support
### Describe the bug

Up until now, using `tsx` (instead of `ts-node`) was working great. The latest version just broke this though, so using `tsx` now no longer enables TS support.

The regression commit is this one:
https://github.com/mikro-orm/mikro-orm/commit/3efdcd0a00d038b2eb24a668329f4b1cea46b2a2

### Reproduction

Try to run a project with `tsx` instead of `ts-node`.

### What driver are you using?

None

### MikroORM version

v6.4.9

### Node.js version

v22.14.0

### Operating system

_No response_

### Validations

- [x] Read the [Contributing Guidelines](https://github.com/mikro-orm/mikro-orm/blob/master/CONTRIBUTING.md).
- [x] Read the [docs](https://mikro-orm.io/docs).
- [x] Check that there isn't [already an issue](https://github.com/mikro-orm/mikro-orm/issues) that reports the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mikro-orm/mikro-orm/discussions) or join our [Discord](https://discord.gg/w8bjxFHS7X).
- [x] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by B4nan**
Closes #6491

### CODE REVIEW

File: packages/core/src/utils/Utils.ts [hunk 1]
```diff
@@ -800,8 +800,12 @@ export class Utils {
       || !!process.env.TS_JEST // check if ts-jest is used (works only with v27.0.4+)
       || !!process.env.VITEST // check if vitest is used
       || !!process.versions.bun // check if bun is used
-      || process.argv.slice(1).some(arg => arg.includes('ts-node')) // registering ts-node runner
-      || process.execArgv.some(arg => arg === 'ts-node/esm'); // check for ts-node/esm module loader
+      || process.argv.slice(1).some(arg => arg.endsWith('.ts')) // executing `.ts` file
```
Comment (B4nan) [inline packages/core/src/utils/Utils.ts:803]: @DASPRiD what do you think about this bit? not sure if it can be dangerous, but it seems quite good, we would also detect if people try to use native node stripping on a TS file this way, and it would be up to them to decide if its working for them (it wont parse decorators, that was the reason to change this logic in the first place, but it can work with `EntitySchema`)

Comment (DASPRiD) [reply packages/core/src/utils/Utils.ts:803]: Hmmm, this looks a little fragile in my opinion. There are a lot more typescript extensions to consider here I think. From the top of my head I can think of "tsx", "mts" and "cts". So maybe `/\.(tsx|[mc]?ts)$/.test(arg)`?
