### PR TITLE
fix(mysql): apply current context when fetching `auto_increment_increment`

### LINKED ISSUE #5279: Cannot Create Entity in MySQL When Max Pool Set to 1
### Describe the bug

An application hangs when using MySQL to create a new instance of an entity and the max pool size is set to 1.

This is because the SQL statement:

`show variables like 'auto_increment_increment'`

Is not using the current context and this request creates a new connection to the database.

The PR fixes this issue by passing the context to the `getAutoIncrementIncrement` function.

### Reproduction

Test case and PR to follow.

### What driver are you using?

@mikro-orm/mysql

### MikroORM version

6.1.5

### Node.js version

20.4.0

### Operating system

OSX

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/mikro-orm/mikro-orm/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://mikro-orm.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/mikro-orm/mikro-orm/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mikro-orm/mikro-orm/discussions) or join our [Slack](https://join.slack.com/t/mikroorm/shared_invite/enQtNTM1ODYzMzM4MDk3LWM4ZDExMjU5ZDhmNjA2MmM3MWMwZmExNjhhNDdiYTMwNWM0MGY5ZTE3ZjkyZTMzOWExNDgyYmMzNDE1NDI5NjA).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by steve-keep**
Closes #5279

### CODE REVIEW

File: packages/mysql/src/MySqlDriver.ts [hunk 1]
```diff
@@ -31,8 +31,9 @@ export class MySqlDriver extends AbstractSqlDriver<MySqlConnection, MySqlPlatfor
   override async nativeInsertMany<T extends object>(entityName: string, data: EntityDictionary<T>[], options: NativeInsertUpdateManyOptions<T> = {}): Promise<QueryResult<T>> {
     options.processCollections ??= true;
     const res = await super.nativeInsertMany(entityName, data, options);
-    const pks = this.getPrimaryKeyFields(entityName);
-    const autoIncrementIncrement = await this.getAutoIncrementIncrement();
+		const pks = this.getPrimaryKeyFields(entityName);
+		const ctx = options.ctx;
```
Comment (B4nan) [inline packages/mysql/src/MySqlDriver.ts:35]:
```suggestion
    const pks = this.getPrimaryKeyFields(entityName);
    const ctx = options.ctx;
```

**Review by B4nan — CHANGES_REQUESTED** [review]
nice, thanks! same fix needs to be applied to the mariadb driver

**Review by B4nan — APPROVED** [review]
