### PR TITLE
fix(core): ensure `em.insertMany` returns array of PKs for a single item too

### LINKED ISSUE #5179: v6.0.5 insertMany
### Describe the bug

when i insert only one record, because i expecting 1 or more items i use insertMany, but when i insert only one, then returned ids insertIds are undefined and it should return insertedId from response in array
```{ affectedRows: 1, insertId: 1, row: { id: 1 }, rows: [ { id: 1 } ] }```

### Reproduction

// Works as a workaround
await em.insertMany(
          Test,
          [{
            test: "test"
          }],
        );

### What driver are you using?

@mikro-orm/postgresql

### MikroORM version

6.0.5

### Node.js version

v18.18.2

### Operating system

mac

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/mikro-orm/mikro-orm/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://mikro-orm.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/mikro-orm/mikro-orm/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mikro-orm/mikro-orm/discussions) or join our [Slack](https://join.slack.com/t/mikroorm/shared_invite/enQtNTM1ODYzMzM4MDk3LWM4ZDExMjU5ZDhmNjA2MmM3MWMwZmExNjhhNDdiYTMwNWM0MGY5ZTE3ZjkyZTMzOWExNDgyYmMzNDE1NDI5NjA).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by tkudlicka**
Closes #5179

### CODE REVIEW

File: packages/core/src/EntityManager.ts [hunk 1]
```diff
@@ -1410,7 +1410,10 @@ export class EntityManager<D extends IDatabaseDriver = IDatabaseDriver> {
     data.forEach(row => em.validator.validateParams(row, 'insert data'));
     const res = await em.driver.nativeInsertMany<Entity>(entityName, data as EntityData<Entity>[], { ctx: em.transactionContext, ...options });
 
-    return res.insertedIds!;
+    if(!res.insertedIds) {
+      return [res.insertId];
+    }
+    return res.insertedIds;
```
Comment (B4nan) [inline packages/core/src/EntityManager.ts:1416]:
```suggestion
    if (res.insertedIds) {
      return res.insertedIds;
    }

    return [res.insertId];
```
