### PR TITLE
fix(core): support FK as PK in `Collection.getIdentifiers()`

### LINKED ISSUE #1224: PK as FK with References & getIdentifiers
**Describe the bug**
The collection method "getIdentifiers" returns an array of references instead of the expecting ids:
~~~ts
      [ Reference { entity: Ref<Node> { id: 1 } } ]
~~~
This derivates from the type declaration.

**To Reproduce**
#1224

**Expected behavior**
~~~ts
      [ 1 ]
~~~
 instead of
~~~ts
      [ Reference { entity: Ref<Node> { id: 1 } } ]
~~~

**Versions**
| Dependency | Version |
| node | 15.4.0 |
| typescript | 4.1.2 |
| mikro-orm | 4.3.4  |
| postgresql |  8.5.1 |

### PR DESCRIPTION
**Pull request by ml1nk**
Closes #1224

### CODE REVIEW

File: packages/core/src/entity/ArrayCollection.ts [hunk 1]
```diff
@@ -58,7 +58,13 @@ export class ArrayCollection<T, O> {
 
     field = field ?? this.property.targetMeta!.serializedPrimaryKey;
 
-    return this.getItems().map(i => i[field as keyof T]) as unknown as U[];
```
Comment (ml1nk) [inline packages/core/src/entity/ArrayCollection.ts:61]: Replaced this.getItems() with items as it seems to be faster.

File: packages/core/src/entity/ArrayCollection.ts [hunk 2]
```diff
@@ -58,7 +58,13 @@ export class ArrayCollection<T, O> {
...
+    return items.map(i => {
+      let e = i[field as keyof T] as unknown as U;
+      while (e instanceof Reference) {
```
Comment (ml1nk) [inline packages/core/src/entity/ArrayCollection.ts:63]: I have never tested nested PK as FK with References, but think it is possible.

File: packages/core/src/entity/ArrayCollection.ts (hunk 1 above)
Comment (B4nan) [reply packages/core/src/entity/ArrayCollection.ts:61]: please revert that, first of all its unrelated to this issue, second this would disable check in `Collection.getItems()`.

Comment (ml1nk) [reply packages/core/src/entity/ArrayCollection.ts:61]: It's reverted. I understand the first point, but not the second. What's the difference of calling getItems() once (few lines above this one) or twice in the same method/tick? The check in Collection is called anyways.

**Review by B4nan — CHANGES_REQUESTED** [review]
what is wrong with using `wrap(e).getPrimaryKey()`? it should handle the recursion automatically, as well as the reference wrapper

File: packages/core/src/entity/ArrayCollection.ts (hunk 1 above)
Comment (ml1nk) [reply packages/core/src/entity/ArrayCollection.ts:61]: I make a separate refactor PR for this, thanks.

File: packages/core/src/entity/ArrayCollection.ts (hunk 2 above)
Comment (ml1nk) [reply packages/core/src/entity/ArrayCollection.ts]: Refactored

File: packages/core/src/entity/ArrayCollection.ts [hunk 3]
```diff
@@ -58,7 +58,13 @@ export class ArrayCollection<T, O> {
 
     field = field ?? this.property.targetMeta!.serializedPrimaryKey;
 
-    return this.getItems().map(i => i[field as keyof T]) as unknown as U[];
+    return this.getItems().map(i => {
+      let e = i[field as keyof T] as unknown as U;
+      while (e instanceof Reference) {
+        e = e.unwrap()[this.property.targetMeta!.properties[field as string].targetMeta!.serializedPrimaryKey];
```
[the remark this answers is not in the document]
Comment (ml1nk) [reply packages/core/src/entity/ArrayCollection.ts]: > wrap(e).getPrimaryKey()

I couldn't access getPrimaryKey() like this and i assume that, like in my first try, it returns the raw object even if it should be serialized (like a test expects).

[the remark this answers is not in the document]
Comment (B4nan) [reply packages/core/src/entity/ArrayCollection.ts]: This way it works fine for me (and your test case is passing):

```ts
  getIdentifiers<U extends IPrimaryKey = Primary<T> & IPrimaryKey>(field?: string): U[] {
    const items = this.getItems();

    if (items.length === 0) {
      return [];
    }

    field = field ?? this.property.targetMeta!.serializedPrimaryKey;

    return items.map(i => {
      if (Utils.isEntity(i[field as keyof T], true)) {
        return wrap(i[field as keyof T], true).getPrimaryKey();
      }

      return i[field as keyof T];
    }) as unknown as U[];
  }
```

[the remark this answers is not in the document]
Comment (ml1nk) [reply packages/core/src/entity/ArrayCollection.ts]: I was missing wrap(...,true). Thanks for your help, i updated my pr appropriately.

**Comment by B4nan** [comment]
Thanks!
