### PR TITLE
fix(core) : fix primary key serialization when a custom type is involved

### LINKED ISSUE #6179: Serialization with forceObject: true does not apply primary key custom type
### Describe the bug

Serialization using `forceObject: true` doesn't apply custom type on foreign key. 

### Reproduction

```ts
import { MikroORM, serialize, Entity, ManyToOne, Platform, PrimaryKey, Property, Ref, Type } from '@mikro-orm/sqlite';

export class IDStoredAsInteger extends Type<string, number> {

  convertToDatabaseValue(value: string): number {
    return parseInt(value);
  }

  convertToJSValue(value: number): string {
    return `${value}`;
  }

  getColumnType() {
    return `integer`;
  }

}

@Entity()
class User {

  @PrimaryKey({ type: IDStoredAsInteger })
  id!: string;

  @Property({ unique: true })
  email!: string;

  @ManyToOne(() => User, { nullable: true })
  bestFriend?: Ref<User>;

}

let orm: MikroORM;

beforeAll(async () => {
  orm = await MikroORM.init({
    dbName: ':memory:',
    entities: [User],
  });
  await orm.schema.createSchema();
});

afterAll(async () => {
  await orm.close(true);
});

it('should apply custom type when serializing primary key of non-populated relation', async () => {
  const totoUser = orm.em.create(User, {
    email: 'toto@test.com',
  });
  orm.em.create(User, {
    email: 'yolo@test.com',
    bestFriend: totoUser,
  });
  await orm.em.flush();

  const u1 = await orm.em.fork().findOneOrFail(User, { email: 'yolo@test.com' });
  const dto1 = serialize(u1);
  expect(typeof dto1.id).toBe('string');
  expect(dto1.bestFriend).toBeDefined();
  expect(typeof dto1.bestFriend).toBe('string');

  const u2 = await orm.em.fork().findOneOrFail(User, { email: 'yolo@test.com' }, { populate: ['bestFriend'] });
  const dto2 = serialize(u2);
  expect(typeof dto2.id).toBe('string');
  expect(dto2.bestFriend).toBeDefined();
  expect(typeof dto2.bestFriend).toBe('string');
});
```

### What driver are you using?

@mikro-orm/postgresql

### MikroORM version

6.3

### Node.js version

v20.11.1

### Operating system

Macos

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/mikro-orm/mikro-orm/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://mikro-orm.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/mikro-orm/mikro-orm/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mikro-orm/mikro-orm/discussions) or join our [Discord](https://discord.gg/w8bjxFHS7X).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by leonardbinet**
Closes #6179

### CODE REVIEW

File: packages/core/src/serialization/EntitySerializer.ts [hunk 1]
```diff
@@ -229,7 +229,7 @@ export class EntitySerializer {
       return this.serialize(child, childOptions) as EntityValue<T>;
     }
 
-    const pk = wrapped.getPrimaryKey(true)!;
+    const pk = wrapped.getPrimaryKey(false)!;
```
Comment (B4nan) [inline packages/core/src/serialization/EntitySerializer.ts:232]: the very same issue will be in implicit serialization, lets alter the test to try that too and fix that too, its in `EntityTransformer` class

```suggestion
    const pk = wrapped.getPrimaryKey()!;
```

**Comment by B4nan** [comment]
It was indeed a bit more complicated 🙃

**Comment by leonardbinet** [comment]
ahah indeed 😅 , thx a lot for the fix 🙏
