### PR TITLE
fix(core): handle Bun path lookup for native ES decorators

### LINKED ISSUE #7381: Bun 1.3.10 direct TS execution with ES decorators falls back to entity name in `lookupPathFromDecorator`
### Describe the bug

using tools
- ES decorators from `@mikro-orm/decorators/es`
- `TsMorphMetadataProvider`

execute my server with `bun run --watch ./src/app.ts`, MikroORM fails to read entities with error

```
[discovery] - processing entity Task (Task)
163 |       path = path.replace(new RegExp(`^${outDirRelative}`), '');
164 |     }
165 |     path = this.stripRelativePath(path);
166 |     const source = this.sources.find(s => s.getFilePath().endsWith(path));
167 |     if (!source && validate) {
168 |       throw new MetadataError(
                  ^
MetadataError: Source file './Task' not found. Check your 'entitiesTs' option and verify you have 'compilerOptions.declaration' enabled in your 'tsconfig.json'. If you are using webpack, see https://bit.ly/35pPDNn
 entity: undefined,
```

### Reproduction

https://github.com/changchanghwang/mikro-orm-fallback

### What driver are you using?

@mikro-orm/mysql

### MikroORM version

    "@mikro-orm/core": "^7.0.4",     "@mikro-orm/decorators": "^7.0.4",     "@mikro-orm/mysql": "^7.0.4",     "@mikro-orm/reflection": "^7.0.4"

### Node.js version

bun 1.3.10, node 22.22.1

### Operating system

mac os

### Validations

- [x] Read the [Contributing Guidelines](https://github.com/mikro-orm/mikro-orm/blob/master/CONTRIBUTING.md).
- [x] Read the [docs](https://mikro-orm.io/docs).
- [x] Check that there isn't [already an issue](https://github.com/mikro-orm/mikro-orm/issues) that reports the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mikro-orm/mikro-orm/discussions) or join our [Discord](https://discord.gg/w8bjxFHS7X).
- [x] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by changchanghwang**
## Summary
- fix decorator path lookup on Bun@1.3.10~ ([native Es decorators](https://bun.com/blog/bun-v1.3.10#tc39-standard-es-decorators))
- support stack frames that omit column numbers during path extraction
- test codes for this pr

Closes #7381

### CODE REVIEW

File: packages/decorators/src/utils.ts [hunk 1]
```diff
@@ -167,7 +171,7 @@ export function lookupPathFromDecorator(name: string, stack?: string[]): string
   }
 
   try {
-    const re = /\(.+\)/i.exec(stack[line]) ? /\((.*):\d+:\d+\)/ : /at\s*(.*):\d+:\d+$/;
+    const re = /\(.+\)/i.exec(stack[line]) ? /\((.*?)(?::\d+){1,2}\)/ : /at\s*(.*?)(?::\d+){1,2}$/;
```
Comment (B4nan) [inline packages/decorators/src/utils.ts:174]: Why limit the size to `{1,2}`? Are you sure it can't be a bigger number?

Comment (changchanghwang) [reply packages/decorators/src/utils.ts:174]: The previous regex already assumed at most two numeric segments, since it only matched :line:column. 
`:\d+:\d+`

If you think the current form is a bit less explicit, I can rewrite it to something like `:\d+(?::\d+)?`

Comment (B4nan) [reply packages/decorators/src/utils.ts:174]: Oh, this is for groups, I thought its for the digits of the line number.

Comment (changchanghwang) [reply packages/decorators/src/utils.ts:174]: Exactly, haha. When you asked me at first, I surprised too :)

**Comment by changchanghwang** [comment]
i don't know where 1 missing line is...

**Comment by B4nan** [comment]
image

https://app.codecov.io/gh/mikro-orm/mikro-orm/pull/7382?dropdown=coverage&src=pr&el=h1&utm_medium=referral&utm_source=github&utm_content=checks&utm_campaign=pr+comments&utm_term=mikro-orm

Take a look, but don't try too hard, I am fine with a missed line too (or a coverage ignore hint).

**Comment by changchanghwang** [comment]
> Take a look, but don't try too hard, I am fine with a missed line too (or a coverage ignore hint).

It looks like that line became a missing line because the existing stack trace is now covered by bunWrapLine.

since Bun’s stack trace format might still hit that logic, I think it would be better to keep the logic in place. 

As for the test case, it would probably make sense to add it later once we know the exact stack trace that triggers it.
