### PR TITLE
fix(seeder): fix type of Factory methods

### LINKED ISSUE #3062: Factory / Seeder: makeOne & createOne expect wrong type for IdentifiedReference (wrappedReference)
**Describe the bug**
We used the syntax described in [the docu: "Reference Wrapper"](https://mikro-orm.io/docs/entity-references#better-type-safety-with-referencet-wrapper) and now we cannot satisfy the typeScript types anymore when creating data in our seeder.

**To Reproduce**

```ts
@Entity()
export class Child {
    @ManyToOne({
        entity: () => Parent,
        wrappedReference: true, // new
    })
    parent: IdentifiedReference<Parent>; // before we had: `parend: Parent` and it worked with the Seeders
}

const child = new ChildFactory(orm.em).make({
    ...otherProps,
    parent: parent, // TS Error
});

// -> TS Error:
// Type 'Parent' is not assignable to type '{ id: number; } & Reference<Parent>'.
// Type 'Parent' is missing the following properties from type 'Reference<Parent>': entity, load, set, unwrap, and 5 more.
```

**The same with:**
- `Factory.create`
- `Factory.createOne`
- `Factory.make`
- `Factory.makeOne`

**Expected behaviour**
I want to be able to create an entity with a ManyToOne Relationship by simply passing the other entity or its id.
Just like it works when calling:

```ts
this.orm.em.create(Child, {...otherProps, parent});
```

**Suggestion**
We could give the methods in Factory<T> similar types as entityManager.create:

```diff
- makeOne(overrideParameters?: Partial<T>): T;
+ makeOne(overrideParameters?: RequiredEntityData<T>): T;
```

**Versions**

| Dependency | Version |
| - | - |
| mikro-orm | 5.1.1 |

### PR DESCRIPTION
**Pull request by tobiaskraus**
As asked by [B4nan](https://github.com/B4nan) in related issue, I opened this PR.

Closes #3062

### Description

See issue above

### Tests

Only types were changed, so no useful test which I can think of can cover that besides TypeScript itself (`yarn tsc-check-tests`). Existing tests are running successful.

### Docu

Only [here](https://mikro-orm.io/docs/seeding#entity-factories) the documentation could be updated, but I think for the majority of people a simple partial is enough - so let's keep it how it is instead of:

```diff
- definition(faker: Faker): Partial<Author>
+ definition(faker: Faker): Partial<RequiredEntityData<Author>>
```

### CODE REVIEW

**Comment by B4nan** [comment]
thanks!

File: packages/seeder/src/Factory.ts [hunk 1]
```diff
@@ -9,9 +9,9 @@ export abstract class Factory<T> {
 
   constructor(private readonly em: EntityManager) { }
 
-  protected abstract definition(faker: Faker): Partial<T>;
+  protected abstract definition(faker: Faker): Partial<RequiredEntityData<T>>;
```
Comment (B4nan) [inline packages/seeder/src/Factory.ts:12]: oops, i got distracted and didnt really review this one :D 

we should use just `EntityData` instead of `Partial<RequiredEntityData>`, it should do exactly the same. will fix it in a minute
