### PR TITLE
fix(query-builder): fix `qb.insert()/update()` on embeddables in inline mode

### LINKED ISSUE #3325: Issue updating embedded with query builder
Hello, I think I've found an issue when using embeddables with the query builder

**Describe the bug**
Using the query builder to update an embedded does not produce the expected request 

**Stack trace**
```
SqliteError: update `main_entity` set `vo` = '{"test":"toto"}' where `id` = 1 - no such column: vo

      223 |       this.emit('query', Object.assign({ __knexUid, __knexTxId }, obj));
      224 |
    > 225 |       return MonkeyPatchable.QueryExecutioner.executeQuery(connection, obj, this);
          |                                               ^
      226 |     };
      227 |
      228 |     TableCompiler.prototype.raw = function (this: any, query: string) {

      at Database.prepare (node_modules/better-sqlite3/lib/methods/wrappers.js:5:21)
      at Client_BetterSQLite3._query (node_modules/knex/lib/dialects/better-sqlite3/index.js:30:34)
      at Object.executeQuery (node_modules/knex/lib/execution/internal/query-executioner.js:37:17)
      at Client_BetterSQLite3.Client.query (packages/knex/src/AbstractSqlConnection.ts:225:47)
      at Runner.query (node_modules/knex/lib/execution/runner.js:130:36)
      at ensureConnectionCallback (node_modules/knex/lib/execution/internal/ensure-connection-callback.js:13:17)
      at Runner.ensureConnection (node_modules/knex/lib/execution/runner.js:307:20)
      at async Runner.run (node_modules/knex/lib/execution/runner.js:30:19)
      at async BetterSqliteConnection.executeQuery (packages/core/src/connections/Connection.ts:109:19)
      at async BetterSqliteConnection.execute (packages/knex/src/AbstractSqlConnection.ts:116:17)
```

**To Reproduce**
1. Create a basic entity
2. Add a simple embedded object to it
3. Create a query builder on the main entity and try to update the embedded

`.qb(MainEntity).update({ vo: { test: 'toto' } })`

**Expected behavior**
The generated request should look like `update `main_entity` set `vo_test` = "toto" where `id` = 1`

**Additional context**
(edit) PR with tests: https://github.com/mikro-orm/mikro-orm/pull/3326

**Versions**

| Dependency | Version |
| - | - |
| node | v16.12.0 |
| typescript | 4.7.4 |
| mikro-orm | master |
| your-driver | pg in project, sqlite for tests |

Thank you for your attention

### PR DESCRIPTION
**Pull request by fathyb**
Fix a bug where inserting embeddables using a `QueryBuilder` would throw the following error:
```
  ● insert an object with embeddable using a QueryBuilder

    SqliteError: insert into `user` (`id`, `settings`) select 1 as `id`, '[object Object]' as `settings` union all select 2 as `id`, '[object Object]' as `settings` - table user has no column named settings

      223 |       this.emit('query', Object.assign({ __knexUid, __knexTxId }, obj));
      224 |
    > 225 |       return MonkeyPatchable.QueryExecutioner.executeQuery(connection, obj, this);
          |                                               ^
      226 |     };
      227 |
      228 |     TableCompiler.prototype.raw = function (this: any, query: string) {

      at Database.prepare (node_modules/better-sqlite3/lib/methods/wrappers.js:5:21)
      at Client_BetterSQLite3._query (node_modules/knex/lib/dialects/better-sqlite3/index.js:30:34)
      at Object.executeQuery (node_modules/knex/lib/execution/internal/query-executioner.js:37:17)
      at Client_BetterSQLite3.Client.query (packages/knex/src/AbstractSqlConnection.ts:225:47)
      at Runner.query (node_modules/knex/lib/execution/runner.js:123:36)
      at ensureConnectionCallback (node_modules/knex/lib/execution/internal/ensure-connection-callback.js:13:17)
      at Runner.ensureConnection (node_modules/knex/lib/execution/runner.js:300:20)
      at async Runner.run (node_modules/knex/lib/execution/runner.js:30:19)
      at async BetterSqliteConnection.executeQuery (packages/core/src/connections/Connection.ts:109:19)
      at async BetterSqliteConnection.execute (packages/knex/src/AbstractSqlConnection.ts:116:17)
```

Closes #3325.

### CODE REVIEW

**Comment by B4nan** [comment]
What about update queries, does it help there too? There is a recent issue about it.

**Comment by fathyb** [comment]
Yep! I added a new test which fails with the following error if I revert the fix:
```
  ● update an object with embeddable using a QueryBuilder

    SqliteError: update `user` set `settings` = '[object Object]' where `id` = 1 - no such column: settings

      223 |       this.emit('query', Object.assign({ __knexUid, __knexTxId }, obj));
      224 |
    > 225 |       return MonkeyPatchable.QueryExecutioner.executeQuery(connection, obj, this);
          |                                               ^
      226 |     };
      227 |
      228 |     TableCompiler.prototype.raw = function (this: any, query: string) {

      at Database.prepare (node_modules/better-sqlite3/lib/methods/wrappers.js:5:21)
      at Client_BetterSQLite3._query (node_modules/knex/lib/dialects/better-sqlite3/index.js:30:34)
      at Object.executeQuery (node_modules/knex/lib/execution/internal/query-executioner.js:37:17)
      at Client_BetterSQLite3.Client.query (packages/knex/src/AbstractSqlConnection.ts:225:47)
      at Runner.query (node_modules/knex/lib/execution/runner.js:123:36)
      at ensureConnectionCallback (node_modules/knex/lib/execution/internal/ensure-connection-callback.js:13:17)
      at Runner.ensureConnection (node_modules/knex/lib/execution/runner.js:300:20)
      at async Runner.run (node_modules/knex/lib/execution/runner.js:30:19)
      at async BetterSqliteConnection.executeQuery (packages/core/src/connections/Connection.ts:109:19)
      at async BetterSqliteConnection.execute (packages/knex/src/AbstractSqlConnection.ts:116:17)
```

File: packages/knex/src/query/QueryBuilderHelper.ts [hunk 1]
```diff
@@ -670,4 +638,55 @@ export class QueryBuilderHelper {
     return [QueryType.SELECT, QueryType.COUNT].includes(type);
   }
 
+  private mapData(data: Dictionary, properties: undefined | Record<string, EntityProperty>, options: {convertCustomTypes: boolean}) {
```
Comment (B4nan) [inline packages/knex/src/query/QueryBuilderHelper.ts:641]:
```suggestion
  private mapData(data: Dictionary, properties?: Dictionary<EntityProperty>, convertCustomTypes?: boolean) {
```

File: packages/knex/src/query/QueryBuilderHelper.ts [hunk 2]
```diff
@@ -102,41 +102,9 @@ export class QueryBuilderHelper {
...
-
-      if (!prop.customType && (Array.isArray(data[k]) || Utils.isPlainObject(data[k]))) {
-        data[k] = JSON.stringify(data[k]);
-      }
-
-      if (prop.fieldNames) {
-        Utils.renameKey(data, k, prop.fieldNames[0]);
-      }
-    });
+    data = this.mapData(data, meta?.properties, { convertCustomTypes });
```
Comment (B4nan) [inline packages/knex/src/query/QueryBuilderHelper.ts:107]:
```suggestion
    data = this.mapData(data, meta?.properties, convertCustomTypes);
```

File: packages/knex/src/query/QueryBuilderHelper.ts [hunk 3]
```diff
@@ -670,4 +638,55 @@ export class QueryBuilderHelper {
...
+      const prop = properties[k];
+
+      if (!prop) {
+        return;
+      }
+
+      if (prop.embeddedProps && !prop.object) {
+        const copy = data[k];
+        delete data[k];
+        Object.assign(data, this.mapData(copy, prop.embeddedProps, options));
```
Comment (B4nan) [inline packages/knex/src/query/QueryBuilderHelper.ts:658]:
```suggestion
        Object.assign(data, this.mapData(copy, prop.embeddedProps, convertCustomTypes));
```

File: packages/knex/src/query/QueryBuilderHelper.ts [hunk 4]
```diff
@@ -670,4 +638,55 @@ export class QueryBuilderHelper {
...
+
+      if (prop.joinColumns && Array.isArray(data[k])) {
+        const copy = data[k];
+        delete data[k];
+        prop.joinColumns.forEach((joinColumn, idx) => data[joinColumn] = copy[idx]);
+
+        return;
+      }
+
+      if (prop.customType && options.convertCustomTypes && !this.platform.isRaw(data[k])) {
```
Comment (B4nan) [inline packages/knex/src/query/QueryBuilderHelper.ts:671]:
```suggestion
      if (prop.customType && convertCustomTypes && !this.platform.isRaw(data[k])) {
```

**Review by B4nan — APPROVED** [review]

**Comment by B4nan** [comment]
Thanks!
